# Generated by Django 2.2 on 2020-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='actual_time',
            field=models.DurationField(null=True, verbose_name='実際時間'),
        ),
        migrations.AlterField(
            model_name='target',
            name='expectation_time',
            field=models.DurationField(verbose_name='予想時間'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_content',
            field=models.TextField(max_length=1000, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_status',
            field=models.IntegerField(choices=[(1, '未着手'), (2, '進行中'), (3, '終了')], default=1, verbose_name='学習ステータス'),
        ),
        migrations.AlterField(
            model_name='target',
            name='understanding_level',
            field=models.IntegerField(choices=[(1, '全然'), (2, '何となく'), (3, '大体わかった'), (4, '結構わかった'), (5, '完璧')], default=1, verbose_name='理解度'),
        ),
    ]
