# Generated by Django 2.2 on 2020-04-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectivepage', '0002_auto_20200421_1142'),
        ('targetpage', '0002_auto_20200421_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('target_name', 'objective')},
        ),
    ]
