# Generated by Django 2.2 on 2020-04-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpage', '0003_auto_20200421_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='actual_time',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='実際時間'),
        ),
        migrations.AlterField(
            model_name='target',
            name='expectation_time',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='予想時間'),
        ),
    ]
