# Generated by Django 2.2 on 2020-04-21 02:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectivepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objective',
            unique_together={('object_name', 'user')},
        ),
    ]
